#!/bin/bash

REPOSITORY="$HOME/.mydotfiles"
BACKUPDIR="$HOME/.dfmsh-back"
IGNOREFILE="$REPOSITORY/.dfmshignore"


function _install () 
{
for file in $(_list_files); do
  file=$(basename $file)

  local file_type=$(file --mime-type -b "$HOME/$file");
  if [ "$file_type" = "inode/symlink" ]; then
    continue;
  else
    if [ -e "$HOME/$file" ]; then
      [ -e $BACKUPDIR ] || mkdir $BACKUPDIR
      mv "$HOME/$file" "$BACKUPDIR/$file"
    fi
    ln -s $REPOSITORY/$file $HOME/$file
    echo $file " INSTALLED."
  fi
done
}

function _uninstall () 
{
  for file in $(_list_files); do

    local file_type=$(file --mime-type -b "$HOME/$file");
    if [ "$file_type" = "inode/symlink" ]; then
      rm "$HOME/$file"
      echo $file " UNINSTALLED."
    fi

    if [ -e "$BACKUPDIR/$file" ]; then 
      mv "$BACKUPDIR/$file" $HOME
      echo $file " RESTORED."
    fi

  done
}

function _list_files () 
{
  local ignore_file=`cat $IGNOREFILE | xargs`
  local ignore_file="$ignore_file .dfmshignore .. ."

  local files=`ls -a $REPOSITORY | xargs`
  local final_files=""

  for file in $files; do
    file=$(basename $file)
    [[ $ignore_file =~ $file ]] && continue;
    final_files+=$file
  done
  [ "$final_files" = "" ] && echo "No input files" && exit  
  echo $final_files
}

case "$1" in
  install)   _install    ;;
  uninstall) _uninstall  ;;
  list)      _list_files ;;
esac
# vim: ft=sh
